

- name: get service route interface name
  shell: ip route | grep 10.0.6.0/24 | grep -oP '(?<=dev\s)\w+'
  register: SERVICE_INTERFACE

- name: set oai component interfaces
  set_fact:
    ENB_INTERFACE: "{{SERVICE_INTERFACE.stdout}}"

- name: overwrite oai eNodeB configs
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:    
    - { src: 'oaisim.j2', dest: '/home/ubuntu/openairinterface5g/targets/PROJECTS/GENERIC-LTE-EPC/CONF/enb.band7.generic.oaisim.local_mme.conf' }

- name: set hosts
  lineinfile:
    name: /etc/hosts
    line: "{{item.line}}"
    regexp: "{{item.regex}}"
  with_items:
    - { regex: "{{ENB_HOST}}", line: '{{ENB_PRIVATE_IP}} {{ENB_HOST}}' }
 
